
USE [quartz]
GO

-- Drop the constraints
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS  WHERE CONSTRAINT_NAME='FK_QRTZ_JOB_DEFINITION_NEXT_JOB_DEFN')
ALTER TABLE [dbo].[QRTZ_JOB_DEFINITION] DROP CONSTRAINT [FK_QRTZ_JOB_DEFINITION_NEXT_JOB_DEFN]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS  WHERE CONSTRAINT_NAME='FK_QRTZ_JOB_DEFINITION_JOB_TYPE')
ALTER TABLE [dbo].[QRTZ_JOB_DEFINITION] DROP CONSTRAINT [FK_QRTZ_JOB_DEFINITION_JOB_TYPE]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS  WHERE CONSTRAINT_NAME='FK_QRTZ_JOB_DEFINITION_QRTZ_MISFIRE_DEFINITIONS')
ALTER TABLE [dbo].[QRTZ_JOB_DEFINITION] DROP CONSTRAINT [FK_QRTZ_JOB_DEFINITION_QRTZ_MISFIRE_DEFINITIONS]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS  WHERE CONSTRAINT_NAME='FK_QRTZ_JOB_TYPE_PARAMETERS_LINK_QRTZ_JOB_TYPE_PARAMETERS')
ALTER TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS_LINK] DROP CONSTRAINT [FK_QRTZ_JOB_TYPE_PARAMETERS_LINK_QRTZ_JOB_TYPE_PARAMETERS]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS  WHERE CONSTRAINT_NAME='FK_QRTZ_JOB_TYPE_PARAMETERS_LINK_QRTZ_JOB_TYPE')
ALTER TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS_LINK] DROP CONSTRAINT [FK_QRTZ_JOB_TYPE_PARAMETERS_LINK_QRTZ_JOB_TYPE]
GO


-- Drop the tables
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_JOB_DEFINITION]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [dbo].[QRTZ_JOB_DEFINITION]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_JOB_TYPE]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [dbo].[QRTZ_JOB_TYPE]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_JOB_TYPE_PARAMETERS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_JOB_TYPE_PARAMETERS_LINK]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS_LINK]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[QRTZ_MISFIRE_DEFINITIONS]') AND OBJECTPROPERTY(id, N'ISUSERTABLE') = 1)
DROP TABLE [dbo].[QRTZ_MISFIRE_DEFINITIONS]
GO


CREATE TABLE [dbo].[QRTZ_JOB_TYPE] (
	[JOB_TYPE_ID] [uniqueidentifier] NOT NULL,
	[JOB_TYPE] [nvarchar](40) NOT NULL,
	[JOB_TYPE_DESCRIPTION] [nvarchar](4000) NOT NULL,
	-- Assembly information is used from dynamic loading of libraries. This enables
	-- the scheduler to load in new libraries without stoping and starting the scheduler.
	[ASSEMBLY_PATH] [nvarchar] (4000) NULL,
	[ASSEMBLY_FILE_NAME] [nvarchar] (100) NULL   -- Full
 CONSTRAINT [PK_QRTZ_JOB_TYPE] PRIMARY KEY CLUSTERED 
(
	[JOB_TYPE_ID] ASC
) ON [PRIMARY] 
)
GO
ALTER TABLE [dbo].[QRTZ_JOB_TYPE] ADD  CONSTRAINT [DF_QRTZ_JOB_TYPE_JOB_TYPE_ID]  DEFAULT (newsequentialid()) FOR [JOB_TYPE_ID]
GO

CREATE TABLE [dbo].[QRTZ_MISFIRE_DEFINITIONS] (
	[MISFIRE_ID] [uniqueidentifier] NOT NULL,
	[MISFIRE_NAME] [nvarchar](40) NOT NULL,
	[MISFIRE_DESCRIPTION] [nvarchar](4000) NOT NULL
 CONSTRAINT [PK_QRTZ_MISFIRE_DEFINITIONS] PRIMARY KEY CLUSTERED 
(
	[MISFIRE_ID] ASC
) ON [PRIMARY] 
)
GO
ALTER TABLE [dbo].[QRTZ_MISFIRE_DEFINITIONS] ADD  CONSTRAINT [DF_QRTZ_MISFIRE_DEFINITIONS_MISFIRE_ID]  DEFAULT (newsequentialid()) FOR [MISFIRE_ID]
GO

CREATE TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS] (
	[JOB_TYPE_PARAM_ID] [uniqueidentifier] NOT NULL,
	[KEY] [nvarchar](150) NOT NULL,
	[VALUE] [nvarchar](150) NOT NULL,
	[DESCRIPTION] [nvarchar](4000) NOT NULL,
 CONSTRAINT [PK_QRTZ_JOB_TYPE_PARAMETERSS] PRIMARY KEY CLUSTERED 
(
	[JOB_TYPE_PARAM_ID] ASC
) ON [PRIMARY] 
)
GO
ALTER TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS] ADD  CONSTRAINT [DF_QRTZ_JOB_TYPE_PARAMETERS_JOB_TYPE_PARAM_ID]  DEFAULT (newsequentialid()) FOR [JOB_TYPE_PARAM_ID]
GO


CREATE TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS_LINK] (
	[JOB_TYPE_ID] [uniqueidentifier] NOT NULL,
	[JOB_TYPE_PARAM_ID] [uniqueidentifier] NOT NULL
 CONSTRAINT [PK_QRTZ_JOB_TYPE_PARAMETERS_LINK] PRIMARY KEY CLUSTERED 
(
	[JOB_TYPE_ID] ASC,
	[JOB_TYPE_PARAM_ID] ASC
) ON [PRIMARY] 
)
GO

-- Note: See qrtz_job_details and qrtz_triggers for columns, datatype, and nullable
-- TODO add SCHED_NAME nvarchar(100) NOT NULL when support more than one Scheduler running
CREATE TABLE [dbo].[QRTZ_JOB_DEFINITION] (
    [JOB_DEFINITION_ID] [uniqueidentifier] NOT NULL,
	[JOB_NAME] [nvarchar](150) NOT NULL,          -- Such as CheckCustomerConfig
	[JOB_GROUP] [nvarchar](150) NOT NULL,         -- Such as EMV
	[JOB_TYPE_ID] [uniqueidentifier] NOT NULL,
	[JOB_PARAM] [nvarchar](4000) NULL,            -- Job parameter
	[JOB_DESCRIPTION] [nvarchar](4000) NOT NULL,
	[TRIGGER_NAME] [nvarchar](150) NOT NULL,
	[TRIGGER_PRIORITY] [int] NULL,
	[CRON_TRIGGER_EXPRESSION] [nvarchar](150) NULL,   -- Using cron to schedule triggers. Leave empty if just a definition
	[MISFIRE_ID][uniqueidentifier] NULL,				-- FK to the MISFIRE INSTRUCTION LIST Table
	[IS_DURABLE] [bit] NOT NULL,    
	[SCHEDULE_JOB] bit NOT NULL,		-- This is a switch to tell scheduler to leave this definition alone or add it
	[PARENT_JOB_DEFINITION_ID] [uniqueidentifier] NULL,			-- This is how to create parent/child releationships between job definition records
	[IS_ASYNCHRONOUS] bit NOT NULL					-- This switch tells the scheduler to either run this job after the parent finish or anytime
 CONSTRAINT [PK_QRTZ_JOB_DEFINITION] PRIMARY KEY CLUSTERED 
(
	[JOB_DEFINITION_ID] ASC
) ON [PRIMARY] 
)
GO
ALTER TABLE [dbo].[QRTZ_JOB_DEFINITION] ADD  CONSTRAINT [DF_QRTZ_JOB_DEFINITION_JOB_DEFINITION_ID]  DEFAULT (newsequentialid()) FOR [JOB_DEFINITION_ID]
GO

-- FK on parent/child job definition records
ALTER TABLE [dbo].[QRTZ_JOB_DEFINITION] ADD
  CONSTRAINT [FK_QRTZ_JOB_DEFINITION_NEXT_JOB_DEFN] FOREIGN KEY
  (
    [PARENT_JOB_DEFINITION_ID]
  ) REFERENCES [dbo].[QRTZ_JOB_DEFINITION] (
    [JOB_DEFINITION_ID]
  )
GO

-- FK on JOB_DEFINITION.JOB_TYPE_ID and JOB_TYPE.JOB_TYPE_ID
ALTER TABLE [dbo].[QRTZ_JOB_DEFINITION] ADD
  CONSTRAINT [FK_QRTZ_JOB_DEFINITION_JOB_TYPE] FOREIGN KEY
  (
    [JOB_TYPE_ID]
  ) REFERENCES [dbo].[QRTZ_JOB_TYPE] (
    [JOB_TYPE_ID]
  )
GO

-- FK on QRTZ_JOB_DEFINITION.MISFIRE_ID and QRTZ_MISFIRE_DEFINITIONS.MISFIRE_ID
ALTER TABLE [dbo].[QRTZ_JOB_DEFINITION] ADD
  CONSTRAINT [FK_QRTZ_JOB_DEFINITION_QRTZ_MISFIRE_DEFINITIONS] FOREIGN KEY
  (
    [MISFIRE_ID]
  ) REFERENCES [dbo].[QRTZ_MISFIRE_DEFINITIONS] (
    [MISFIRE_ID]
  )
GO

-- Next set of constraints are FK on the Parameters Link table 
ALTER TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS_LINK] ADD
  CONSTRAINT [FK_QRTZ_JOB_TYPE_PARAMETERS_LINK_QRTZ_JOB_TYPE_PARAMETERS] FOREIGN KEY
  (
    [JOB_TYPE_PARAM_ID]
  ) REFERENCES [dbo].[QRTZ_JOB_TYPE_PARAMETERS] (
    [JOB_TYPE_PARAM_ID]
  )
GO

ALTER TABLE [dbo].[QRTZ_JOB_TYPE_PARAMETERS_LINK] ADD
  CONSTRAINT [FK_QRTZ_JOB_TYPE_PARAMETERS_LINK_QRTZ_JOB_TYPE] FOREIGN KEY
  (
    [JOB_TYPE_ID]
  ) REFERENCES [dbo].[QRTZ_JOB_TYPE] (
    [JOB_TYPE_ID]
  )
GO